### ISSUE TITLE
Match of multiple files with brace expansion notation does not work with one extension

### ISSUE THREAD

**Issue by el777** [editorconfig/editorconfig-core-js#92] opened 2021-07-17 18:18 UTC
The following config will match a `.js` file
```
[*.{js,py}]
indent_style = space
indent_size = 2
```
whereas
the following will not:
```
[*.{js}]
indent_style = space
indent_size = 2
```

Expected behavior is `[*.{js}]` would match a `.js` file which is the behavior in other editorconfig core libraries.

**Comment by hildjj** [comment] 2022-10-11 14:53
This is by design, in order to be compatible with bash.  See https://github.com/juliangruber/brace-expansion/issues/56#issuecomment-918963909.

(we use minimatch, which uses brace-expansion for this piece of functionality)

I think I agree with the logic, so I'm going to close this.  But feel free to comment more and we'll reopen it if we come up with a good argument.

**Closed** 2022-10-11 14:53 UTC
